# Generated by Django 2.0 on 2018-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章标签名称')),
                ('slug', models.SlugField(unique=True)),
                ('tag_desc', models.TextField(max_length=240, verbose_name='文章标签描述')),
            ],
        ),
    ]
