# Generated by Django 2.0 on 2018-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_body',
            field=models.TextField(default=10, editable=False, verbose_name='文章内容html格式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='img_upload',
            field=models.ImageField(default=10, height_field='url_height', upload_to='', verbose_name='上传图片', width_field='url_width'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='文章内容markdown格式'),
        ),
    ]
