# Generated by Django 2.0 on 2018-11-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181112_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_upload',
            field=models.ImageField(upload_to='', verbose_name='上传图片'),
        ),
    ]
