# Generated by Django 2.0 on 2018-11-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181112_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_upload',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='markdown_body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_url',
        ),
    ]
