# Generated by Django 2.0 on 2018-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_read_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='toc',
            field=models.TextField(editable=False, max_length=400, verbose_name='导航'),
        ),
    ]
