# Generated by Django 2.0 on 2018-11-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181117_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='toc',
            field=models.TextField(editable=False, verbose_name='导航'),
        ),
    ]
