# Generated by Django 2.0 on 2018-11-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181117_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='toc',
        ),
    ]
